#! /bin/sh
killall picom
killall sxhkd

bspc monitor HDMI1 -d 1 2 3 4 5 
bspc monitor eDP1 -d 6 7 8 9 10 

bspc config border_width 0
bspc config window_gap   4 
 
# some extra top space for bar
bspc config top_padding    22
bspc config right_padding  0
bspc config left_padding   0
bspc config bottom_padding 0

bspc config split_ratio             0.55
bspc config borderless_monocle      true
bspc config gapless_monocle         true
bspc config focus_by_distance       true
bspc config history_aware_focus     true

bspc config focus_follows_pointer true
bspc config pointer_follows_focus false
bspc config pointer_follows_monitor true

bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
bspc config merge_overlapping_monitor true

bspc rule -a Ulauncher border=off 
bspc rule -a plasmashell state=floating
bspc rule -a Plasma state=floating
bspc rule -a plasma-desktop state=floating
bspc rule -a krunner state=floating
bspc rule -a Kmix state=floating
bspc rule -a Klipper state=floating
bspc rule -a Plasmoidviewer state=floating
bspc rule -a Chromium state=monocle desktop='^1'

sxhkd &
picom -b &
#launcher &

#nitrogen --restore 
